FROM node:16.19.1-bullseye-slim
WORKDIR /app
COPY package.json package.json
COPY yarn.lock yarn.lock
RUN yarn install --production=false --ignore-scripts
COPY . .
ENV DATABASE_URL='replace-me'
RUN yarn build
EXPOSE 3000
CMD [ "yarn", "start" ]